### ISSUE TITLE
Mark with akka, akka-http tags in ScalaIndex

### ISSUE THREAD

**Issue by ktoso** [lomigmegard/akka-http-cors#10]
Hi there,
awesome project, thanks!

Would you be able to add the `akka-http` and `akka-http-extension` tags on https://index.scala-lang.org/lomigmegard/akka-http-cors so it would be more discoverable to users of akka http?

This way it'd be listed in: 
- http://akka.io/community/
- https://index.scala-lang.org/search?q=keywords:akka-http-extension

Thanks!

**Comment by lomigmegard** [comment]
Done :)

**Comment by ktoso** [comment]
Great 👍
