### ISSUE TITLE
Issue with headerValueByName()

### ISSUE THREAD

**Issue by elsener** [lomigmegard/akka-http-cors#11]
Hello,

I'm trying to add CORS support for my akka http API while using akka-http-cors: https://github.com/lomigmegard/akka-http-cors

Everything is working fine when I'm basically adding cors support to a simple route but it seems that adding headerValueByName(...) to the route breaks cors support and I can't figure out why.

The full story can be found here:
http://stackoverflow.com/questions/40723715/cors-in-akka-http-with-headervaluebyname-issue-akka-http-cors

**Comment by lomigmegard** [comment]
Hi, 

Please debug your server route with a tool like `curl` to see the actual response from the server, not the JavaScript's interpretation.

    curl -X GET -H "Origin: http://example.com" -H "myheader: test" http://localhost:9000/ping

I suspect that your custom header is not properly sent in the HTTP request. The `headerValueByName` directive will then reject the request. The rejection bubbles up (skipping the `cors` directive) to be finally handled by the default rejection handler. The CORS-related headers are therefore not responded.

You should have your rejection and exception handlers __inside__ the `cors` directive, not outside (like with the default ones). 

Please look in my StackOverflow response for an example.

**Comment by elsener** [comment]
Thanks a lot, you were perfectly right! The issue was in the query and in the way rejections were handled by my implementation on the server. Problem solved.

**Comment by lomigmegard** [comment]
No problem :)
