### ISSUE TITLE
Update akka-http 10.2.0 to 10.2.1

### ISSUE THREAD

**Issue by DawidWalczak** [lomigmegard/akka-http-cors#128]
Hi,
while compiling my project I got the following warning:
Here are other dependency conflicts that were resolved:
 * com.typesafe.akka:akka-http_2.13:10.2.1 is selected over 10.2.0
      +- default:postgres_service_2.13:0.1.0-SNAPSHOT        (depends on 10.2.1)
      +- de.heikoseeberger:akka-http-circe_2.13:1.35.2         (depends on 10.2.1)
      +- ch.megard:akka-http-cors_2.13:1.1.0                        (depends on 10.2.0)

Its possible to upgrade your akka-http dependency to 10.2.1?

Thanks in advance.

**Comment by lomigmegard** [comment]
Hi Dawid,

This warning can safely be ignored (and in large projects I can assure you it's actually very common). Akka and akka-http follow strict binary compatibility between their releases, especially for a `patch` bump. See the [compatibility guidelines](https://doc.akka.io/docs/akka-http/current/compatibility-guidelines.html) for more information.

I will nevertheless plan a new release, I was actually waiting for the `10.2.2` version that should come out soon.

**Comment by DawidWalczak** [comment]
Hi,
thanks for the fast response.
Okay, so let's wait until 10.2.2.
Your,
Dawid

**Comment by lomigmegard** [comment]
@DawidWalczak I just released version `1.1.1` with akka-http `10.2.2`. Should be synced to Maven central soon.

**Comment by DawidWalczak** [comment]
Great!, thanks for the info.
Best Regards,
Dawid.

Lomig Mégard <notifications@github.com> schrieb am Sa., 12. Dez. 2020,
12:12:
