### ISSUE TITLE
Read CORS settings from configuration file

### ISSUE THREAD

**Issue by lomigmegard** [lomigmegard/akka-http-cors#13]
Use the same pattern as in `akka.http.impl.settings.ServerSettingsImpl` to load the settings from a `.conf` file. 
Provide a `reference.conf` with default values.

**Comment by jiminhsieh** [comment]
Have you been work on this? I think I could try to implement it. :)

**Comment by lomigmegard** [comment]
@jiminhsieh I already started working on this, but got caught on something else.
I will clean the code a bit and push it to a feature branch this way we can discuss how to finish it.

**Comment by jiminhsieh** [comment]
I just thought if you have not been working on this, I could **try** to help it. :)

**Comment by rodrigorn** [comment]
Is there any update on this front?

**Comment by lomigmegard** [comment]
@rodrigorn I have some code locally, but havn't spend the time to polish the implementation as it is low priority. 

If you have a use-case for it I can get back to it sooner :)

**Comment by rodrigorn** [comment]
Is there anything I can do to help? I'm adding cors support to my api right now and I'm reading all the settings from a config file

**Comment by rodrigorn** [comment]
Hi @lomigmegard I've been working on this [topic](https://github.com/rodrigorn/akka-http-cors/commit/0ff5dc525d5dde6b5ba72a0887c883687d8839dc), could you checkit out and tell me if wich kind of test would you like to see?

**Comment by lomigmegard** [comment]
@rodrigorn Thanks for the help! 
Initial comments:
- Make sure the API you add is mirrored for the Java side too.
- The default values should only be in the conf file, no more in the code (I can handle this one in a second step if needed)
- ... and more small tweaks about parsing the values that we can fix later.

Fix the two main comments above then create a PR, to be able to iterate over it.
I will take care of updating the documentation/changelog when the PR is merged.

**Comment by rodrigorn** [comment]
@lomigmegard regarding the second point, just to confirm do you want me to delete all the previous default values?

**Comment by lomigmegard** [comment]
@rodrigorn Yes the `defaultSettings` definition should load the values from the file.
For that you can use `ConfigFactory.defaultReference()`. 
Using `ConfigFactory.load()` can also be used, but we should perhaps rename the variable then because it's not default anymore.

We can tweak that later.

**Comment by rodrigorn** [comment]
Hi @lomigmegard please check this [changes](https://github.com/rodrigorn/akka-http-cors/commit/324537cae86d671d0073d4eb4ee815ea7daa8674), could you check why the tests are not passing?
The java side uses `defaultSettings` from scala so it should be ok.

**Comment by lomigmegard** [comment]
@rodrigorn create a PR this way I can see the test results.

**Comment by lomigmegard** [comment]
Release version `0.3.0` with this improvement.
