### ISSUE TITLE
Upgrade to akka-http 10.0.10

### ISSUE THREAD

**Issue by greenhost87** [lomigmegard/akka-http-cors#23]
Please provide new build with akka-http 10.0.10 as dependency

**Comment by ktoso** [comment]
You do realise that Akka-http is binary backwards compatible and using a lib published for 10.0.9 such as this one is fully compatible with 10.0.10 though right?

**Comment by greenhost87** [comment]
@ktoso Yes, but last version in https://mvnrepository.com/artifact/ch.megard/akka-http-cors_2.11 is 0.2.1, 10.0.5 is backwards compatible with 10.0.10 ?

**Comment by lomigmegard** [comment]
@greenhost87 all the minor version should indeed be backwards compatible. 
I will still publish a new version soon to bump all the dependencies.
