### ISSUE TITLE
Should CORS be abandoned?

### ISSUE THREAD

**Issue by jackzhp** [lomigmegard/akka-http-cors#24]
I think that CORS design is completely unnecessary, stupid, and so should be abandoned. I have laid down my arguments, if you think you know this issue pretty well, would you please look at it, and comment it.

https://github.com/jackzhp/CORS-should-retire
or
http://blog.sina.com.cn/s/blog_93b70ae70102wxe8.html

Hope you can contribute to the change!

**Comment by lomigmegard** [comment]
Hey, 
Thanks for the interest. I am neither for or against the CORS mechanism. It is indeed quite old and perhaps not that suited for the current Web. Independently, the `akka-http` ecosystem still needs this implementation to comply with existing browsers.

Letting this issue open for more discussions :)

**Comment by jackzhp** [comment]
@lomigmegard is a very nice open minded guy. CORS is needed since most web servers do not do origin/referrer based authorization check, so the origin based authorization check is delegated to browsers. If all web servers, or web servers with critical data, do origin based authorization check at server side, then CORS is indeed not necessary. But at current situation, it is needed if old approach such as js or jsonp is not used.
