### ISSUE TITLE
Apache Pekko support

### ISSUE THREAD

**Issue by pjfanning** [lomigmegard/akka-http-cors#258]
Thanks for maintaining this lib.

Is there any chance that you would consider producing a pekko version? Apache Pekko is still under development but there are usable snapshots at https://repository.apache.org/content/groups/snapshots/org/apache/pekko/

**Comment by lomigmegard** [comment]
Hi, I am indeed following the Pekko project closely. I was waiting for a bit more appetite and stability. 

I am also pondering if I should continue supporting both or just migrate it all to pekko (`apache-pekko-cors`) 🤔 

I am busy for the next two weeks, but I will think about it and publish some kind of solution in the horizon of 3-4 weeks. Let me know if there is a more urgent need to remove some blocker for the Pekko project.

**Comment by pjfanning** [comment]
Thanks @lomigmegard - no urgency on this. I'm just asking, generally, if you are interested in maintaining a pekko equivalent of this lib.

**Comment by lomigmegard** [comment]
@pjfanning I am yes, but as you can see there isn't that much code neither. We could also evaluate moving it under the Apache umbrella project. 

Over the years the main discussions around this library were all related to which default configuration should be used, as it has impact on security when they are not well-understood.

**Comment by pjfanning** [comment]
I'm involved with the Apache Pekko work. I'm a bit wary about taking on more libraries right now. The main reasoning behind the current set of repos that we're migrating is because of the license issue caused by the Lightbend move to a Business Software License. With the number of active contributors, we have our hands full with the existing set of repos.

We'll need to consider the implications where Akka ecosystem lib maintainers are not in a position to produce Pekko variants but we are a distance away from that yet.

Regarding akka-http-cors, I did a quick check and it looks Pekko can be supported fairly readily. I tested using https://github.com/pjfanning/akka-http-cors/commit/2f68c8802f4a8f44ea5806771da74fcf43fb6edd

**Comment by lomigmegard** [comment]
Hey @pjfanning, I created [pekko-http-cors](https://github.com/lomigmegard/pekko-http-cors) as a fork of this repo. 

Please try to use the first `0.0.0-SNAPSHOT` version that I just published, based on the latest Pekko build from March 4th. The repository is https://oss.sonatype.org/content/repositories/snapshots/ch/megard/

**Comment by pjfanning** [comment]
Thanks @lomigmegard - I updated https://github.com/pjfanning/swagger-pekko-http-sample to use your snapshot and it works great. We'll update pekko-grpc in coming days to use pekko-http-cors as well.

**Comment by lomigmegard** [comment]
Great! I will close this issue then. Let's use the new [repo](https://github.com/lomigmegard/pekko-http-cors) for the upcoming coordination or issues, if any.

**Comment by mdedetrich** [comment]
PR for pekko-grpc is already up at https://github.com/apache/incubator-pekko-grpc/pull/45, thanks for the work!
