### ISSUE TITLE
cors only seems to work with one route

### ISSUE THREAD

**Issue by kornelc** [lomigmegard/akka-http-cors#26]
Am I using the API wrong?

This doesn't work:

<pre>
 val api = cors(){
      get {
        path("page") {
          parameters('from.as[String], 'length.as[Int]) { (from, length) =>
            complete {
              write(table.page(from, length))
            }
          }
        }
      }
      get {
        path("headings") {
          complete {
            write(table.headings)
          }
        }
      }
  }
</pre>

But this does:
<pre>
 val api = cors(){
      get {
        path("page") {
          parameters('from.as[String], 'length.as[Int]) { (from, length) =>
            complete {
              write(table.page(from, length))
            }
          }
        }
      }
  }
</pre>

**Comment by lomigmegard** [comment]
Hi, 
Nothing to do with the CORS directive, you are missing a `~` to join the two sub-routes.

```
 val api = cors() {
      get {
        ???
      } ~  
      get {
         ???
      }
  }
```
--- 

Note that you could use only one `get` there and join the two `path`s inside.

**Comment by kornelc** [comment]
Thanks!

**Comment by ktoso** [comment]
Please note that you may want to use 
```
concat(
  route1,
  route2
) 
```

In which it's harder to accidentally forget the ~ between two routes (the effect of using concat is the same as ~)
