### ISSUE TITLE
http proxy response with tow origin

### ISSUE THREAD

**Issue by ShuiShengYe** [lomigmegard/akka-http-cors#27]
I code an HTTP reverse proxy app with "akka-http-cors". In response headers, there are two "Access-Control-Allow-Credentials" and "Access-Control-Allow-Origin", like follow.

Access-Control-Allow-Credentials: true
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin:http://support.sparkpos.cn
Access-Control-Allow-Origin:http://support.sparkpos.cn

**Comment by lomigmegard** [comment]
Hi, 

This is probably due to some nested `cors` directives. Are you sure you don't have two `cors` directives in your route? 

I will create a new enhancement issue, the directive could indeed prevent this case by deleting any existing header that fall into his responsibility.

**Comment by lomigmegard** [comment]
Could also be because of your proxy, where the original response already contains the CORS headers.

**Comment by lomigmegard** [comment]
Created #28 that should fix this particular issue.

**Comment by ShuiShengYe** [comment]
@lomigmegard Thanks for your working. It is working now.
