### ISSUE TITLE
Upgrade to akka >= 2.7, akka-http >= 10.5

### ISSUE THREAD

**Issue by alexklibisz** [lomigmegard/akka-http-cors#276]
Hi, thanks for maintaining this library. Are there any plans to upgrade to the BSL versions of akka-http and akka? Are there any plans specifically to _not_ upgrade? Thanks.

**Comment by lomigmegard** [comment]
Hi @alexklibisz , 

Thanks to [akka binary compatibility](https://doc.akka.io/docs/akka-http/current/compatibility-guidelines.html), I would expect the current version of akka-http-cors to work with the newest akka-http* releases. I didn't actually test it though.

Have you given it a try? Do you use Scala 2 or 3?

My problem with upgrading is that at the same time many companies (like mine) are stuck on the Apache-licensed versions, and I would then have to maintain two branches.

**Comment by alexklibisz** [comment]
Thanks! I can confirm akka-http-cors does work with akka-http 10.5.0. As you said, the akka libraries maintain binary compatibility across minor versions. My motivation in ask is just that I like to minimize evictions/conflicts if possible. I think your answer is fair and the status-quo is good enough for now. I'll go ahead and close this.
