### ISSUE TITLE
Library not compatible with Scala 3

### ISSUE THREAD

**Issue by Maurycy-Sokolowski** [lomigmegard/akka-http-cors#280]
Scala 3.2.2 and everything goes fine without "ch.megard" %% "akka-http-cors" % "1.2.0".

When I do below:

libraryDependencies ++= Seq(
    "com.typesafe.akka" %% "akka-actor-typed" % "2.8.3",
    "com.typesafe.akka" %% "akka-stream" % "2.8.3",
    "com.typesafe.akka" %% "akka-http" % "10.5.2",
	"ch.megard" % "akka-http-cors_3" % "1.2.0",
...

I get:

Modules were resolved with conflicting cross-version suffixes in ...

[error]    com.typesafe.akka:akka-http-core _3, _2.13
[error]    com.typesafe.akka:akka-parsing _3, _2.13
[error]    com.typesafe.akka:akka-http _3, _2.13
[error] java.lang.RuntimeException: Conflicting cross-version suffixes in: com.typesafe.akka:akka-http-core, com.typesafe.akka:akka-parsing, com.typesafe.akka:akka-http
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.librarymanagement.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:39)
[error] 	at sbt.librarymanagement.ConflictWarning$.apply(ConflictWarning.scala:19)
[error] 	at sbt.Classpaths$.$anonfun$ivyBaseSettings$71(Defaults.scala:3203)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:832)
[error] (update) Conflicting cross-version suffixes in: com.typesafe.akka:akka-http-core, com.typesafe.akka:akka-parsing, com.typesafe.akka:akka-http

I tried every variation out there including:

	"ch.megard" %% "akka-http-cors" % "1.2.0",

and 

	"ch.megard" % "akka-http-cors_2_13" % "1.2.0",

Still the same error.

**Comment by Maurycy-Sokolowski** [comment]
Also I downgraded akka-http to 10.2.10 and still the same error. What is the solution? I imported the whole source of thios project and recompiled it in Scala 3 to make it work but rather would import the library.

**Comment by lomigmegard** [comment]
Hi @Maurycy-Sokolowski 

Related to #223 , but for now I didn't move the akka version because of the change of license. Thanks to akka binary compatibility the current version works with newer versions of akka and akka-http.

Now for Scala 3 in particular, you can try excluding the transitive dependency, which should resolve the conflict and work as expected:

```
libraryDependencies += "ch.megard" %% "akka-http-cors" % "1.2.0" excludeAll ExclusionRule(organization = "com.typesafe.akka")
```

**Comment by Maurycy-Sokolowski** [comment]
I can confirm it works! Great fix.
