### ISSUE TITLE
Support `Origin: null` in simple/actual requests

### ISSUE THREAD

**Issue by lomigmegard** [lomigmegard/akka-http-cors#31]
Follow-up to the question raised in #30 by @AlessandroEmm.

If the CORS directive supports `Origin: null` in simple/actual requests, it will probably require breaking changes on `CorsRejection`.

Also, it will directly go against the recommendation to avoid returning [`Access-Control-Allow-Origin: null`](https://w3c.github.io/webappsec-cors-for-developers/#avoid-returning-access-control-allow-origin-null). I don't know how big of a problem it is in practice.

First thing is to look at other implementations to see how they handle this case.

**Comment by AlessandroEmm** [comment]
Thing is have no idea as to how deal with the issue when Chrome makes heavy use of null in redirects. I think it's obvious that having actual hostnames as origin would be a better approach, I guess I have to dig into Chromes Source at some point and see why and when they are doing that. I mostly experienced it when I had a thirdparty host redirects to itself. Which is usually the case when using the Implicit Flow with OpenID Connect.

**Comment by lomigmegard** [comment]
@AlessandroEmm Hi, could you review my PR on this issue #32, making sure it solves your specific case?
