### ISSUE TITLE
publish for Scala 2.13.0-M5

### ISSUE THREAD

**Issue by lomigmegard** [lomigmegard/akka-http-cors#40]
https://github.com/scala/scala/releases/tag/v2.13.0-M5

Linked to https://github.com/akka/akka/issues/25105

**Comment by pjfanning** [comment]
akka-http 10.1.7 has been released for scala 2.13.0-M5

**Comment by lomigmegard** [comment]
Published in [0.3.4](https://github.com/lomigmegard/akka-http-cors/releases/tag/v0.3.4)
