### ISSUE TITLE
Provide java support 

### ISSUE THREAD

**Issue by matheuslima** [lomigmegard/akka-http-cors#8]
Today the plugin only allows be used with java. Actually is easy to implement java support, akka http has a route adapter that allows to convert a scala http directive to a java directive. Akka http default java directives can be used as example to implement it.

**Comment by lomigmegard** [comment]
I will have a look soon.

**Comment by jiminhsieh** [comment]
Hi lomigmegard, 
If there is any help I can do, please just let me know! :D

**Comment by lomigmegard** [comment]
Doing good progress on that. Will create a PR for review in the coming days.

**Comment by lomigmegard** [comment]
Hey @jiminhsieh, I you have some spare time you can have a look at #14 :)

**Comment by jiminhsieh** [comment]
Hi @lomigmegard, thanks for your mention. Nice work! I just glimpse what you commit. I noticed you used japi as package name. How about javadsl? It would be similar to the design of Akka-HTTP. I will look in detail in the weekend. :D

**Comment by lomigmegard** [comment]
First commits merged. Still need more documentation update.
Published version `0.2.1-SNAPSHOT` that can be used to test the Java API.

**Comment by meong1234** [comment]
hallow.. is there any for scala 2.11 on version 0.2.1-SNAPSHOT ?

**Comment by lomigmegard** [comment]
@meong1234 oops, thought I did it. Should be available soon when Sonatype syncs its repo with Maven Central.

Feedback on the new Java API are welcome btw.

**Comment by meong1234** [comment]
still failed to create with example.. in corsRejectionHandler :(

**Comment by lomigmegard** [comment]
@meong1234 you need to add the Sonatype snapshot repo:

    resolvers += Resolver.sonatypeRepo("snapshots")

But I will try to publish a `M1` release this weekend to make this easier.

**Comment by MarcMagnin** [comment]
Hi @lomigmegard,
Any package public package to import for the java version? I can't find 0.2.1-SNAPSHOT.
Many thanks!

**Comment by MarcMagnin** [comment]
Ok found out, was just missing the sonatype repo ;)

**Comment by lomigmegard** [comment]
I published version `0.2.1` with Java support. Will be synced with Maven Central soon.
