### ISSUE TITLE
Handling PUT actions for Allow-Origin

### ISSUE THREAD

**Issue by mebigfatguy** [lomigmegard/akka-http-cors#86]
I'm getting "Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

So assuming i need to inject cors handling (in java) like

       final CorsSettings settings = CorsSettings.defaultSettings().withAllowedOrigins(HttpOriginRange.create(HttpOrigin.create("http", Host.create("*"))));
        return CorsDirectives.cors(settings, () ->
            pathPrefix(PATH, () -> concat(
                path(PathMatchers.segment(RouteDirectory.UPLOAD)
                                .slash(PathMatchers.segment()
                                 ),(token)-> upload(token,context)),
                path(PathMatchers.segment(RouteDirectory.DOWNLOAD)
                                .slash(PathMatchers.segment()
                                 ),(token)-> withRangeSupport(() -> download(token,context)))
                ))
            );

now i realize "*" isn't good, but i'm just trying to get anything working.... This didn't seem to effect anything. Am i doing this wrong?

**Comment by lomigmegard** [comment]
Hi, 
The default settings should work for you, allowing any Origin. If you are using other http method than `GET, POST, HEAD, OPTIONS`, you have to add them in the settings (the preferred way being to change your `application.conf`).

Please look at the Java example at [CorsServer.java](https://github.com/lomigmegard/akka-http-cors/blob/master/akka-http-cors-example/src/main/java/ch/megard/akka/http/cors/javadsl/CorsServer.java).

**Comment by mebigfatguy** [comment]
Yes this is a PUT., i'll look at adding an  application.conf and just using defaults, then. thanks.

**Comment by mebigfatguy** [comment]
ah, id don't need to mess with allowed origins at all, i just need to add

    allowed-methods = ["GET", "POST", "PUT", "HEAD", "OPTIONS"]
